# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170609_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='extra_credit_image_editor'),
        ),
    ]
