# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170609_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='accounts/assets/extra_credit_image_editor'),
        ),
    ]
