# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170610_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='assets/images'),
        ),
    ]
